### ISSUE TITLE
Too many "Links" dictionaries inside a Redfish object 

### ISSUE THREAD

**Issue by rherrell** [OFMFWG/OFMF-Reference#21]
The Endpoint object "Resources/Fabrics/NVMeoF/Endpoints/D2-E2/index.json" has these two "Links" dict objects....
The first looks correct.  The second is empty, and should not be present.  And the object's @odataID is incorrect (as is the ID, I assume).  I haven't actually posted any connections using this API emulator to any of the default endpoints, but if this json file was created by the emulator that would be a bug in the emulator.  If these json files were created by hand, they are just incorrect.  Either way, the emulator is feeding clients incorrectly configured Endpoint objects which corrupt their view of the fabric resources. 

"Links": {
      "Connections": [{
        "@odata.id": "/redfish/v1/Fabrics/NVMeoF/Connections/3"
      },
      {
        "@odata.id": "/redfish/v1/Fabrics/NVMeoF/Connections/1"
        }]
    },
 "Links": {},
 "@odata.id": "/redfish/v1/Fabrics/NVMeoF/Endpoints/D1-E2",

**Comment by rahlvers** [comment]
Correct - should be:

"Links": {
"Connections": [{
"@odata.id": "/redfish/v1/Fabrics/NVMeoF/Connections/3"
},
{
"@odata.id": "/redfish/v1/Fabrics/NVMeoF/Connections/1"
}]
},

"@odata.id": "/redfish/v1/Fabrics/NVMeoF/Endpoints/D2-E2",

I believe this is all just a manually created Endpoint.

**Comment by christian-pinto** [comment]
Hi @rherrell, @rahlvers is right. This is due to a file that was committed (https://github.com/OFMFWG/OFMF-Reference/commit/0860161796147efdf462755b5d329e4ce52874d1) without checking it is properly formatted, and there is indeed a double `Links`. 

At some point we should remove all those static resources altogether, and move to resources that are instead dynamically discovered through agents.
